{{- range .Values.priorityClasses -}}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .name }}
value: {{ .value | int }}
preemptionPolicy: {{ .preemptionPolicy }}
description: {{ .description }}
{{- end }}
